version: '3'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel  # You can install additional plugins here
      GF_AUTH_ANONYMOUS_ENABLED: "true"           # Enable anonymous access for simplicity
    depends_on:
      - prometheus

  response-time-exporter:
    build: ./response_time_exporter  # Build your exporter Docker image
    ports:
      - 8000:8000
